"""Build script generator.

Generates build.bat (MSVC) or build.sh (MinGW) with correct compiler flags
matching the selected mitigations, architecture, and optional ROP companion DLL.
"""

from target_builder.src.config import Architecture, Compiler, ServerConfig, VulnType


def generate(config: ServerConfig) -> str:
    """Generate build script content for the server.

    Args:
        config: Server configuration.

    Returns:
        Complete build script content as a string.
    """
    if config.compiler == Compiler.MINGW:
        return _generate_mingw(config)
    return _generate_msvc(config)


def _generate_msvc(config: ServerConfig) -> str:
    """Generate build.bat for MSVC cl.exe."""
    arch_label = "x86" if config.arch == Architecture.X86 else "x64"
    prompt_type = (
        "x86 Native Tools" if config.arch == Architecture.X86 else "x64 Native Tools"
    )

    # Server source file
    src_file = config.output_file if config.output_file else "server.cpp"
    exe_name = src_file.rsplit(".", 1)[0] + ".exe"

    # Compiler flags
    cl_flags = ["/EHsc"]
    if config.stack_canary:
        cl_flags.append("/GS")
    else:
        cl_flags.append("/GS-")

    # Linker flags
    link_flags = ["ws2_32.lib"]

    if config.dep:
        link_flags.append("/NXCOMPAT")
    else:
        link_flags.append("/NXCOMPAT:NO")

    if config.aslr:
        link_flags.append("/DYNAMICBASE")
    else:
        link_flags.append("/DYNAMICBASE:NO")

    link_flags.append(f"/BASE:0x{config.base_address:08X}")

    if config.arch == Architecture.X86:
        if config.safe_seh:
            link_flags.append("/SAFESEH")
        else:
            link_flags.append("/SAFESEH:NO")

    cl_line = (
        f"cl.exe {' '.join(cl_flags)} {src_file} "
        f"/Fe:{exe_name} /link {' '.join(link_flags)}"
    )

    lines = [
        "@echo off",
        "REM Generated by target_builder - FOR AUTHORIZED SECURITY TESTING ONLY",
        f"REM Architecture: {arch_label}",
        f"REM Run from: Visual Studio {prompt_type} Command Prompt",
        "",
        f"echo [*] Compiling {src_file} ({arch_label})...",
        cl_line,
        "",
        "if %ERRORLEVEL% NEQ 0 (",
        "    echo [-] Compilation failed",
        "    exit /b 1",
        ")",
        f"echo [+] Built {exe_name}",
    ]

    # ROP DLL build command
    if config.rop_dll.enabled:
        from target_builder.src.templates.rop_dll import generate_dll_build_command

        dll_cmd = generate_dll_build_command(config.rop_dll)
        dll_src = config.rop_dll.output_file
        dll_name = dll_src.rsplit(".", 1)[0] + ".dll"

        lines.extend(
            [
                "",
                f"echo [*] Compiling {dll_src} (ROP helper DLL)...",
                dll_cmd,
                "",
                "if %ERRORLEVEL% NEQ 0 (",
                "    echo [-] DLL compilation failed",
                "    exit /b 1",
                ")",
                f"echo [+] Built {dll_name}",
            ]
        )

    lines.extend(
        [
            "",
            "echo.",
            "echo [+] Build complete.",
        ]
    )

    return "\n".join(lines) + "\n"


def _generate_mingw(config: ServerConfig) -> str:
    """Generate build.sh for MinGW cross-compilation."""
    import os

    arch_label = "x86" if config.arch == Architecture.X86 else "x64"

    # Cross-compiler selection
    if config.arch == Architecture.X86:
        compiler = "i686-w64-mingw32-g++"
    else:
        compiler = "x86_64-w64-mingw32-g++"

    # Server source file — use basename for portable build scripts
    src_file = os.path.basename(config.output_file) if config.output_file else "server.cpp"
    exe_name = src_file.rsplit(".", 1)[0] + ".exe"

    # Compiler flags
    cxx_flags = []

    # Stack protection
    if config.stack_canary:
        cxx_flags.append("-fstack-protector")
    else:
        cxx_flags.append("-fno-stack-protector")

    # SEH support
    if config.vuln_type == VulnType.SEH:
        cxx_flags.append("-fseh-exceptions")

    # Linker flags
    link_flags = ["-lws2_32", "-static"]

    if config.dep:
        link_flags.append("-Wl,--nxcompat")
    else:
        link_flags.append("-Wl,--disable-nxcompat")

    if config.aslr:
        link_flags.append("-Wl,--dynamicbase")
    else:
        link_flags.append("-Wl,--disable-dynamicbase")

    link_flags.append(f"-Wl,--image-base,0x{config.base_address:08X}")

    # No GCC equivalent for SafeSEH
    safeseh_note = ""
    if config.arch == Architecture.X86 and config.vuln_type == VulnType.SEH:
        safeseh_note = (
            "# Note: SafeSEH has no MinGW equivalent "
            "(only applies to MSVC-compiled binaries)\n"
        )

    flags_str = " ".join(cxx_flags) if cxx_flags else ""
    link_str = " ".join(link_flags)
    compile_line = f"{compiler} {flags_str} {src_file} -o {exe_name} {link_str}"

    lines = [
        "#!/bin/bash",
        "# Generated by target_builder - FOR AUTHORIZED SECURITY TESTING ONLY",
        f"# Architecture: {arch_label}",
        f"# Compiler: {compiler}",
        "# Requires: mingw-w64 cross-compiler",
        "set -e",
        "",
    ]

    if safeseh_note:
        lines.append(safeseh_note.rstrip())

    lines.extend(
        [
            f'echo "[*] Compiling {src_file} ({arch_label}) with MinGW..."',
            compile_line,
            f'echo "[+] Built {exe_name}"',
            "",
            "# To test on Linux:",
            f"# wine ./{exe_name}",
            "",
            'echo "[+] Build complete."',
        ]
    )

    return "\n".join(lines) + "\n"
