"""Build script generator.

Generates build.bat with correct cl.exe flags matching the selected
mitigations, architecture, and optional ROP companion DLL.
"""

from target_builder.src.config import Architecture, ServerConfig


def generate(config: ServerConfig) -> str:
    """Generate build.bat content for the server.

    Args:
        config: Server configuration.

    Returns:
        Complete build.bat content as a string.
    """
    arch_label = "x86" if config.arch == Architecture.X86 else "x64"
    prompt_type = (
        "x86 Native Tools" if config.arch == Architecture.X86 else "x64 Native Tools"
    )

    # Server source file
    src_file = config.output_file if config.output_file else "server.cpp"
    exe_name = src_file.rsplit(".", 1)[0] + ".exe"

    # Compiler flags
    cl_flags = ["/EHsc"]
    if config.stack_canary:
        cl_flags.append("/GS")
    else:
        cl_flags.append("/GS-")

    # Linker flags
    link_flags = ["ws2_32.lib"]

    if config.dep:
        link_flags.append("/NXCOMPAT")
    else:
        link_flags.append("/NXCOMPAT:NO")

    if config.aslr:
        link_flags.append("/DYNAMICBASE")
    else:
        link_flags.append("/DYNAMICBASE:NO")

    link_flags.append(f"/BASE:0x{config.base_address:08X}")

    if config.arch == Architecture.X86:
        if config.safe_seh:
            link_flags.append("/SAFESEH")
        else:
            link_flags.append("/SAFESEH:NO")

    cl_line = (
        f"cl.exe {' '.join(cl_flags)} {src_file} "
        f"/Fe:{exe_name} /link {' '.join(link_flags)}"
    )

    lines = [
        "@echo off",
        "REM Generated by target_builder - FOR AUTHORIZED SECURITY TESTING ONLY",
        f"REM Architecture: {arch_label}",
        f"REM Run from: Visual Studio {prompt_type} Command Prompt",
        "",
        f"echo [*] Compiling {src_file} ({arch_label})...",
        cl_line,
        "",
        "if %ERRORLEVEL% NEQ 0 (",
        "    echo [-] Compilation failed",
        "    exit /b 1",
        ")",
        f"echo [+] Built {exe_name}",
    ]

    # ROP DLL build command
    if config.rop_dll.enabled:
        from target_builder.src.templates.rop_dll import generate_dll_build_command

        dll_cmd = generate_dll_build_command(config.rop_dll)
        dll_src = config.rop_dll.output_file
        dll_name = dll_src.rsplit(".", 1)[0] + ".dll"

        lines.extend(
            [
                "",
                f"echo [*] Compiling {dll_src} (ROP helper DLL)...",
                dll_cmd,
                "",
                "if %ERRORLEVEL% NEQ 0 (",
                "    echo [-] DLL compilation failed",
                "    exit /b 1",
                ")",
                f"echo [+] Built {dll_name}",
            ]
        )

    lines.extend(
        [
            "",
            "echo.",
            "echo [+] Build complete.",
        ]
    )

    return "\n".join(lines) + "\n"
