"""Shell completion script generator for target_builder.

Generates bash and zsh completion scripts by introspecting the argparse
parser, so new flags are automatically included without manual maintenance.
"""

import argparse


def generate_completion(shell: str, parser: argparse.ArgumentParser) -> str:
    """Generate a completion script for the given shell.

    Args:
        shell: "bash" or "zsh".
        parser: Configured ArgumentParser to introspect.

    Returns:
        Complete shell completion script as a string.

    Raises:
        ValueError: If shell type is not supported.
    """
    if shell == "bash":
        return _generate_bash(parser)
    elif shell == "zsh":
        return _generate_zsh(parser)
    raise ValueError(f"Unsupported shell: {shell}")


def _extract_flags(parser: argparse.ArgumentParser):
    """Extract flag info from parser actions.

    Yields (flag, choices, is_boolean, help_text) tuples.
    """
    for action in parser._actions:
        if isinstance(action, argparse._HelpAction):
            continue
        # Get the longest option string (prefer --long over -short)
        flags = [f for f in action.option_strings if f.startswith("--")]
        if not flags:
            continue
        flag = flags[0]
        choices = None
        if action.choices:
            choices = list(action.choices)
        is_boolean = isinstance(action, argparse._StoreTrueAction)
        help_text = action.help or ""
        yield flag, choices, is_boolean, help_text


def _generate_bash(parser: argparse.ArgumentParser) -> str:
    """Generate a bash completion script."""
    all_flags = []
    case_entries = []
    file_flags = []

    for flag, choices, is_boolean, help_text in _extract_flags(parser):
        all_flags.append(flag)
        if choices:
            choices_str = " ".join(str(c) for c in choices)
            case_entries.append(
                f"        {flag})\n"
                f'            COMPREPLY=($(compgen -W "{choices_str}" -- "$cur"))\n'
                f"            return ;;"
            )
        elif not is_boolean and (
            "file" in help_text.lower() or "output" in flag.lower()
        ):
            file_flags.append(flag)

    opts_str = " ".join(all_flags)
    case_block = "\n".join(case_entries)

    file_cases = ""
    if file_flags:
        file_pattern = "|".join(file_flags)
        file_cases = (
            f"        {file_pattern})\n"
            f'            COMPREPLY=($(compgen -f -- "$cur"))\n'
            f"            return ;;"
        )

    return f"""\
# bash completion for target_builder
# Generated by target_builder --generate-completion bash
# Source this file or add to ~/.bash_completion.d/

_target_builder_complete() {{
    local cur prev opts
    cur="${{COMP_WORDS[COMP_CWORD]}}"
    prev="${{COMP_WORDS[COMP_CWORD-1]}}"

    opts="{opts_str}"

    case "$prev" in
{case_block}
{file_cases}
    esac

    COMPREPLY=($(compgen -W "$opts" -- "$cur"))
}}

complete -F _target_builder_complete target_builder
complete -F _target_builder_complete target_builder_cli.py
"""


def _generate_zsh(parser: argparse.ArgumentParser) -> str:
    """Generate a zsh completion script."""
    args_specs = []

    for flag, choices, is_boolean, help_text in _extract_flags(parser):
        # Escape single quotes in help text
        help_clean = help_text.replace("'", "'\\''").split("\n")[0][:60]

        if is_boolean:
            args_specs.append(f"        '{flag}[{help_clean}]'")
        elif choices:
            choices_str = " ".join(str(c) for c in choices)
            args_specs.append(
                f"        '{flag}[{help_clean}]:value:({choices_str})'"
            )
        elif "file" in help_text.lower() or "output" in flag.lower():
            args_specs.append(
                f"        '{flag}[{help_clean}]:file:_files'"
            )
        else:
            args_specs.append(
                f"        '{flag}[{help_clean}]:value:'"
            )

    args_block = " \\\n".join(args_specs)

    return f"""\
#compdef target_builder target_builder_cli.py
# zsh completion for target_builder
# Generated by target_builder --generate-completion zsh
# Place in a directory in your $fpath (e.g. ~/.zsh/completions/)

_target_builder() {{
    _arguments \\
{args_block}
}}

_target_builder "$@"
"""
