"""Shared shell completion script generator.

Generates bash and zsh completion scripts by introspecting an argparse
parser, so new flags are automatically included without manual maintenance.

Used by all tools in the rop_tools suite.
"""

import argparse
from typing import List, Optional, Tuple


def generate_completion(
    shell: str,
    parser: argparse.ArgumentParser,
    tool_names: List[str],
) -> str:
    """Generate a completion script for the given shell.

    Args:
        shell: "bash" or "zsh".
        parser: Configured ArgumentParser to introspect.
        tool_names: List of command names to register completions for
                    (e.g. ["get_rop_gadgets", "get_rop_gadgets.py"]).

    Returns:
        Complete shell completion script as a string.

    Raises:
        ValueError: If shell type is not supported.
    """
    if shell == "bash":
        return _generate_bash(parser, tool_names)
    elif shell == "zsh":
        return _generate_zsh(parser, tool_names)
    raise ValueError(f"Unsupported shell: {shell}")


def _extract_flags(
    parser: argparse.ArgumentParser,
) -> List[Tuple[str, Optional[List[str]], bool, str]]:
    """Extract flag info from parser actions.

    Returns list of (flag, choices, is_boolean, help_text) tuples.
    """
    results = []
    for action in parser._actions:
        if isinstance(action, argparse._HelpAction):
            continue

        # Get the longest option string (prefer --long over -short)
        flags = [f for f in action.option_strings if f.startswith("--")]
        if not flags:
            # Positional argument — skip for completion flags list
            # but could be handled separately
            continue
        flag = flags[0]
        choices = None
        if action.choices:
            choices = list(action.choices)
        is_boolean = isinstance(action, argparse._StoreTrueAction)
        help_text = action.help or ""
        results.append((flag, choices, is_boolean, help_text))
    return results


def _generate_bash(parser: argparse.ArgumentParser, tool_names: List[str]) -> str:
    """Generate a bash completion script."""
    func_name = f"_{tool_names[0]}_complete"
    all_flags = []
    case_entries = []
    file_flags = []

    for flag, choices, is_boolean, help_text in _extract_flags(parser):
        all_flags.append(flag)
        if choices:
            choices_str = " ".join(str(c) for c in choices)
            case_entries.append(
                f"        {flag})\n"
                f'            COMPREPLY=($(compgen -W "{choices_str}" -- "$cur"))\n'
                f"            return ;;"
            )
        elif not is_boolean and (
            "file" in help_text.lower() or "output" in flag.lower()
        ):
            file_flags.append(flag)

    opts_str = " ".join(all_flags)
    case_block = "\n".join(case_entries)

    file_cases = ""
    if file_flags:
        file_pattern = "|".join(file_flags)
        file_cases = (
            f"        {file_pattern})\n"
            f'            COMPREPLY=($(compgen -f -- "$cur"))\n'
            f"            return ;;"
        )

    complete_lines = "\n".join(f"complete -F {func_name} {name}" for name in tool_names)

    return f"""\
# bash completion for {tool_names[0]}
# Generated by {tool_names[0]} --generate-completion bash
# Source this file or add to ~/.bash_completion.d/

{func_name}() {{
    local cur prev opts
    cur="${{COMP_WORDS[COMP_CWORD]}}"
    prev="${{COMP_WORDS[COMP_CWORD-1]}}"

    opts="{opts_str}"

    case "$prev" in
{case_block}
{file_cases}
    esac

    COMPREPLY=($(compgen -W "$opts" -- "$cur"))
}}

{complete_lines}
"""


def _generate_zsh(parser: argparse.ArgumentParser, tool_names: List[str]) -> str:
    """Generate a zsh completion script."""
    func_name = f"_{tool_names[0]}"
    compdef_names = " ".join(tool_names)
    args_specs = []

    for flag, choices, is_boolean, help_text in _extract_flags(parser):
        # Escape single quotes and square brackets in help text
        # Square brackets have special meaning in zsh _arguments specs
        help_clean = help_text.replace("'", "'\\''").split("\n")[0][:60]
        help_clean = help_clean.replace("[", "(").replace("]", ")")

        if is_boolean:
            args_specs.append(f"        '{flag}[{help_clean}]'")
        elif choices:
            choices_str = " ".join(str(c) for c in choices)
            args_specs.append(f"        '{flag}[{help_clean}]:value:({choices_str})'")
        elif "file" in help_text.lower() or "output" in flag.lower():
            args_specs.append(f"        '{flag}[{help_clean}]:file:_files'")
        else:
            args_specs.append(f"        '{flag}[{help_clean}]:value:'")

    args_block = " \\\n".join(args_specs)

    return f"""\
#compdef {compdef_names}
# zsh completion for {tool_names[0]}
# Generated by {tool_names[0]} --generate-completion zsh
# Place in a directory in your $fpath (e.g. ~/.zsh/completions/)

{func_name}() {{
    _arguments \\
{args_block}
}}

{func_name} "$@"
"""


def handle_completion(argv: List[str], parser_builder, tool_names: List[str]) -> bool:
    """Check argv for --generate-completion and handle it.

    Call this before parse_args() to allow completion generation without
    requiring other mandatory arguments.

    Args:
        argv: sys.argv[1:] or equivalent.
        parser_builder: Callable that returns an ArgumentParser.
        tool_names: Command names for the completion script.

    Returns:
        True if completion was handled (caller should exit), False otherwise.
    """
    if "--generate-completion" not in argv:
        return False
    idx = argv.index("--generate-completion")
    if idx + 1 < len(argv) and argv[idx + 1] in ("bash", "zsh"):
        parser = parser_builder()
        print(generate_completion(argv[idx + 1], parser, tool_names))
        return True
    return False
