/*
 * Generated by target_builder - FOR AUTHORIZED SECURITY TESTING ONLY
 * Architecture: x86
 * Compile from: Visual Studio x86 Native Tools Command Prompt
 *
 *   cl.exe /EHsc /GS- server.cpp /link ws2_32.lib /NXCOMPAT /DYNAMICBASE:NO /BASE:0x11110000 /SAFESEH:NO
 [*] Random seed: 1798036930

==================================================
  CHALLENGE PARAMETERS
==================================================
  Vulnerability:  fmtstr
  Architecture:   x86
  Protocol:       rpc
  Buffer size:    460
  Stack layout:   padding=51B (mixed), landing_pad=200B
  Bad chars:      0x00, 0x0a, 0x0d, 0x20, 0x25, 0x26
  Bad char mode:  drop
  Mitigations:    DEP (writeprocessmemory)
  Base address:   0x11110000
  Decoys:         1
  Seed:           1798036930
==================================================

[+] Server source: challenge.cpp
[+] Build script: challenge.bat
[+] Exploit skeleton: exploit.py

 */

#include <winsock2.h>
#include <ws2tcpip.h>
#include <windows.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#pragma comment(lib, "ws2_32.lib")

#define SERVER_PORT 9999
#define RECV_BUF_SIZE 8192
#define BANNER "SyncBridge Data Replication v4.0.1\n"

// Forward declarations
DWORD WINAPI handle_connection(LPVOID lpParam);
int init_winsock();
int filter_bad_chars(char* buf, int len);
void dispatch_rpc(SOCKET client, unsigned short opcode, char* payload, int payload_len);
int recv_exact(SOCKET s, char* buf, int n);
void send_rpc_response(SOCKET client, unsigned short opcode, const char* payload, int payload_len);

// Bad character filter: drop mode
// Silently removes filtered bytes from the input
int filter_bad_chars(char* buf, int len) {
    unsigned char bad_chars[] = { 0x00, 0x0a, 0x0d, 0x20, 0x25, 0x26 };
    int bad_count = 6;
    int write_pos = 0;

    for (int i = 0; i < len; i++) {
        int is_bad = 0;
        for (int j = 0; j < bad_count; j++) {
            if ((unsigned char)buf[i] == bad_chars[j]) {
                is_bad = 1;
                break;
            }
        }
        if (!is_bad) {
            buf[write_pos++] = buf[i];
        }
    }
    buf[write_pos] = '\0';
    return write_pos;
}

// Legitimate use of WriteProcessMemory for function pointer patching
typedef void (*handler_func_t)(void);
static handler_func_t g_handler_table[16] = {0};

void patch_handler_table(int index, handler_func_t new_handler) {
    if (index >= 0 && index < 16) {
        SIZE_T written;
        WriteProcessMemory(
            GetCurrentProcess(),
            &g_handler_table[index],
            &new_handler,
            sizeof(handler_func_t),
            &written
        );
    }
}

// Decoy: MONITOR - copies to stack buffer but with bounds check
void handle_monitor(char* data, int data_len) {
    char buffer[256];
    // Safe: bounded memcpy with minimum of input and buffer size
    int copy_len = data_len < (int)sizeof(buffer) - 1
                   ? data_len : (int)sizeof(buffer) - 1;
    memcpy(buffer, data, copy_len);
    buffer[copy_len] = '\0';
    printf("[*] MONITOR: copied %d of %d bytes (bounded)\n",
           copy_len, data_len);
}

// VULNERABLE FUNCTION - Format string vulnerability
// User input passed directly to printf without format specifier
void vuln_function(SOCKET client, char* payload, int payload_len) {
    filter_bad_chars(data, data_len);
    char response[4096];
    int resp_len;

    // Some local variables on the stack for the attacker to leak
    int secret_value = 0xDEADBEEF;
    char internal_key[] = "S3cretK3y!";
    void* stack_addr = &secret_value;

    (void)internal_key;
    (void)stack_addr;

    // VULNERABLE: printf with user-controlled format string
    // Attacker can use %x/%p to read stack, %n to write
    printf("[*] Processing: ");
    printf(payload);
    printf("\n");

    // Also send the formatted output back to the attacker
    // This lets them see the leaked data over the network
    resp_len = _snprintf(response, sizeof(response) - 1, "Result: ");
    resp_len += _snprintf(response + resp_len, sizeof(response) - resp_len - 1,
                          payload);
    response[resp_len] = '\0';
    strcat(response, "\n");

    send(client, response, (int)strlen(response), 0);
}

void dispatch_rpc(SOCKET client, unsigned short opcode,
                  char* payload, int payload_len) {
    // Vulnerable opcode: 1
    if (opcode == VULN_OPCODE) {
        if (payload_len > 0) {
            vuln_function(client, payload, payload_len);
            send_rpc_response(client, VULN_OPCODE, "OK", 2);
        } else {
            send_rpc_response(client, VULN_OPCODE, "ERR:NO_DATA", 11);
        }
        return;
    }

    // Opcode 0: Ping
    if (opcode == PING_OPCODE) {
        send_rpc_response(client, PING_OPCODE, "PONG", 4);
        return;
    }

    // Opcode 2: Echo
    if (opcode == 2) {
        send_rpc_response(client, 2, payload, payload_len);
        return;
    }

    // Opcode 3: Server stats
    if (opcode == 3) {
        char stats[128];
        int stats_len = _snprintf(stats, sizeof(stats),
                                  "UPTIME:%d", GetTickCount() / 1000);
        send_rpc_response(client, 3, stats, stats_len);
        return;
    }

    // Decoy opcode 10: MONITOR
    if (opcode == 10) {
        if (payload_len > 0) {
            handle_monitor(payload, payload_len);
            send_rpc_response(client, 10, "OK", 2);
        } else {
            send_rpc_response(client, 10, "ERR:NO_DATA", 11);
        }
        return;
    }

    // Unknown opcode
    send_rpc_response(client, opcode, "ERR:UNKNOWN_OP", 14);
}

// RPC message header
#pragma pack(push, 1)
typedef struct {
    unsigned int msg_len;     // Total message length (including header)
    unsigned short opcode;    // Operation code
} rpc_header_t;
#pragma pack(pop)

#define RPC_HEADER_SIZE sizeof(rpc_header_t)
#define VULN_OPCODE 1
#define PING_OPCODE 0
#define INFO_OPCODE 255

// Read exactly n bytes from socket
int recv_exact(SOCKET s, char* buf, int n) {
    int total = 0;
    while (total < n) {
        int received = recv(s, buf + total, n - total, 0);
        if (received <= 0) return -1;
        total += received;
    }
    return total;
}

// Send RPC response: header + payload
void send_rpc_response(SOCKET client, unsigned short opcode,
                       const char* payload, int payload_len) {
    rpc_header_t resp_hdr;
    resp_hdr.msg_len = (unsigned int)(RPC_HEADER_SIZE + payload_len);
    resp_hdr.opcode = opcode;
    send(client, (char*)&resp_hdr, RPC_HEADER_SIZE, 0);
    if (payload && payload_len > 0) {
        send(client, payload, payload_len, 0);
    }
}

DWORD WINAPI handle_connection(LPVOID lpParam) {
    SOCKET client = (SOCKET)lpParam;
    rpc_header_t hdr;
    char payload_buf[RECV_BUF_SIZE];

    // Send banner as ping response on connect
    send_rpc_response(client, PING_OPCODE, BANNER, (int)strlen(BANNER));

    while (1) {
        // Read message header
        if (recv_exact(client, (char*)&hdr, RPC_HEADER_SIZE) < 0) {
            break;
        }

        // Validate message length
        int payload_len = hdr.msg_len - RPC_HEADER_SIZE;
        if (payload_len < 0 || payload_len >= RECV_BUF_SIZE) {
            break;
        }

        // Read payload
        memset(payload_buf, 0, sizeof(payload_buf));
        if (payload_len > 0) {
            if (recv_exact(client, payload_buf, payload_len) < 0) {
                break;
            }
            payload_buf[payload_len] = '\0';
        }

        // Dispatch by opcode
        dispatch_rpc(client, hdr.opcode, payload_buf, payload_len);
    }

    printf("[*] RPC client disconnected\n");
    closesocket(client);
    return 0;
}

int init_winsock() {
    WSADATA wsa_data;
    int result = WSAStartup(MAKEWORD(2, 2), &wsa_data);
    if (result != 0) {
        printf("WSAStartup failed: %d\n", result);
        return 1;
    }
    return 0;
}

int main(int argc, char* argv[]) {
    SOCKET listen_socket = INVALID_SOCKET;
    SOCKET client_socket = INVALID_SOCKET;
    struct sockaddr_in server_addr, client_addr;
    int client_len = sizeof(client_addr);

    printf("[*] %s", BANNER);
    printf("[*] Starting server on port %d...\n", SERVER_PORT);

    if (init_winsock() != 0) return 1;

    listen_socket = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
    if (listen_socket == INVALID_SOCKET) {
        printf("[-] Socket creation failed: %d\n", WSAGetLastError());
        WSACleanup();
        return 1;
    }

    server_addr.sin_family = AF_INET;
    server_addr.sin_addr.s_addr = INADDR_ANY;
    server_addr.sin_port = htons(SERVER_PORT);

    if (bind(listen_socket, (struct sockaddr*)&server_addr, sizeof(server_addr)) == SOCKET_ERROR) {
        printf("[-] Bind failed: %d\n", WSAGetLastError());
        closesocket(listen_socket);
        WSACleanup();
        return 1;
    }

    if (listen(listen_socket, SOMAXCONN) == SOCKET_ERROR) {
        printf("[-] Listen failed: %d\n", WSAGetLastError());
        closesocket(listen_socket);
        WSACleanup();
        return 1;
    }

    printf("[+] Listening on port %d\n", SERVER_PORT);

    while (1) {
        client_socket = accept(listen_socket, (struct sockaddr*)&client_addr, &client_len);
        if (client_socket == INVALID_SOCKET) {
            printf("[-] Accept failed: %d\n", WSAGetLastError());
            continue;
        }

        printf("[+] Connection from %s:%d\n",
               inet_ntoa(client_addr.sin_addr),
               ntohs(client_addr.sin_port));

        // Handle connection in a new thread
        HANDLE thread = CreateThread(
            NULL, 0,
            (LPTHREAD_START_ROUTINE)handle_connection,
            (LPVOID)client_socket, 0, NULL
        );
        if (thread) {
            CloseHandle(thread);
        } else {
            closesocket(client_socket);
        }
    }

    closesocket(listen_socket);
    WSACleanup();
    return 0;
}
