/*
 * Generated by target_builder - FOR AUTHORIZED SECURITY TESTING ONLY
 * Architecture: x86
 * Compile from: Visual Studio x86 Native Tools Command Prompt
 *
 *   cl.exe /EHsc /GS- server.cpp /link ws2_32.lib /NXCOMPAT /DYNAMICBASE:NO /BASE:0x11110000 /SAFESEH:NO

 [*] Random seed: 588536434

==================================================
  CHALLENGE PARAMETERS
==================================================
  Vulnerability:  bof
  Architecture:   x86
  Protocol:       http
  Buffer size:    420
  Stack layout:   padding=121B (none), landing_pad=246B
  Bad chars:      0x00, 0x0a, 0x0d, 0x20, 0x25, 0x26
  Bad char mode:  drop
  Mitigations:    DEP (virtualalloc)
  Base address:   0x11110000
  Decoys:         2
  Seed:           588536434
==================================================

[+] Server source: challenge.cpp
[+] Build script: challenge.bat
[+] Exploit skeleton: exploit.py

 */

#include <winsock2.h>
#include <ws2tcpip.h>
#include <windows.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#pragma comment(lib, "ws2_32.lib")

#define SERVER_PORT 9999
#define RECV_BUF_SIZE 8192
#define BANNER "CloudRelay Proxy Service v1.7\n"

// Forward declarations
DWORD WINAPI handle_connection(LPVOID lpParam);
int init_winsock();
int filter_bad_chars(char* buf, int len);
void dispatch_http(SOCKET client, http_request_t* req);
void send_http_response(SOCKET client, int status, const char* status_text, const char* content_type, const char* body);

// Bad character filter: drop mode
// Silently removes filtered bytes from the input
int filter_bad_chars(char* buf, int len) {
    unsigned char bad_chars[] = { 0x00, 0x0a, 0x0d, 0x20, 0x25, 0x26 };
    int bad_count = 6;
    int write_pos = 0;

    for (int i = 0; i < len; i++) {
        int is_bad = 0;
        for (int j = 0; j < bad_count; j++) {
            if ((unsigned char)buf[i] == bad_chars[j]) {
                is_bad = 1;
                break;
            }
        }
        if (!is_bad) {
            buf[write_pos++] = buf[i];
        }
    }
    buf[write_pos] = '\0';
    return write_pos;
}

// Legitimate use of VirtualAlloc for working buffer
static char* g_work_buffer = NULL;

void init_work_buffer() {
    g_work_buffer = (char*)VirtualAlloc(
        NULL, 65536, MEM_COMMIT | MEM_RESERVE, PAGE_READWRITE
    );
    if (g_work_buffer) {
        memset(g_work_buffer, 0, 65536);
    }
}

// Decoy: QUERY - copies to stack buffer but with bounds check
void handle_query(char* data, int data_len) {
    char buffer[256];
    // Safe: bounded memcpy with minimum of input and buffer size
    int copy_len = data_len < (int)sizeof(buffer) - 1
                   ? data_len : (int)sizeof(buffer) - 1;
    memcpy(buffer, data, copy_len);
    buffer[copy_len] = '\0';
    printf("[*] QUERY: copied %d of %d bytes (bounded)\n",
           copy_len, data_len);
}

// Decoy: OPTIMIZE - heap overflow, not directly exploitable for EIP
void handle_optimize(char* data, int data_len) {
    // Allocates on the heap — overflow here won't overwrite return address
    char* heap_buf = (char*)malloc(256);
    if (heap_buf) {
        strcpy(heap_buf, data);  // Overflow goes to heap, not stack
        printf("[*] OPTIMIZE: stored %d bytes on heap\n", data_len);
        free(heap_buf);
    }
}

// VULNERABLE FUNCTION - Classic stack buffer overflow
// Buffer is 420 bytes, recv allows up to 8192 bytes
void vuln_function(char* req->body, int req->body_len) {
    filter_bad_chars(data, data_len);
    char buffer[420];

    printf("[*] Received %d bytes into %d-byte buffer\n", req->body_len, 420);

    // Server-side payload cap — limits shellcode space after EIP
    int max_process_len = 795;
    if (req->body_len > max_process_len) {
        req->body[max_process_len] = '\0';
    }
    // Vulnerable: strcpy does not check bounds
    strcpy(buffer, req->body);
}

void dispatch_http(SOCKET client, http_request_t* req) {
    // Vulnerable endpoint: POST /vulnerable
    if (_stricmp(req->method, "POST") == 0 &&
        _stricmp(req->path, "/vulnerable") == 0) {
        if (req->body_len > 0) {
            vuln_function(req->body, req->body_len);
            send_http_response(client, 200, "OK",
                             "text/plain", "Processed\n");
        } else {
            send_http_response(client, 400, "Bad Request",
                             "text/plain", "Missing body\n");
        }
        return;
    }

    // GET / - Index page
    if (_stricmp(req->method, "GET") == 0 &&
        (_stricmp(req->path, "/") == 0 || _stricmp(req->path, "/index") == 0)) {
        send_http_response(client, 200, "OK", "text/plain",
                         "Server is running. Use POST to submit data.\n");
        return;
    }

    // GET /status
    if (_stricmp(req->method, "GET") == 0 &&
        _stricmp(req->path, "/status") == 0) {
        char status_buf[256];
        _snprintf(status_buf, sizeof(status_buf),
                 "{\"status\":\"running\",\"uptime\":%d}\n",
                 GetTickCount() / 1000);
        send_http_response(client, 200, "OK",
                         "application/json", status_buf);
        return;
    }

    // GET /help
    if (_stricmp(req->method, "GET") == 0 &&
        _stricmp(req->path, "/help") == 0) {
        send_http_response(client, 200, "OK", "text/plain",
                         "Endpoints: GET /, GET /status, GET /help, POST /vulnerable\n");
        return;
    }

    // Decoy endpoint: POST /query
    if (_stricmp(req->method, "POST") == 0 &&
        _stricmp(req->path, "/query") == 0) {
        if (req->body_len > 0) {
            handle_query(req->body, req->body_len);
            send_http_response(client, 200, "OK",
                             "text/plain", "Processed\n");
        } else {
            send_http_response(client, 400, "Bad Request",
                             "text/plain", "Missing body\n");
        }
        return;
    }

    // Decoy endpoint: POST /optimize
    if (_stricmp(req->method, "POST") == 0 &&
        _stricmp(req->path, "/optimize") == 0) {
        if (req->body_len > 0) {
            handle_optimize(req->body, req->body_len);
            send_http_response(client, 200, "OK",
                             "text/plain", "Processed\n");
        } else {
            send_http_response(client, 400, "Bad Request",
                             "text/plain", "Missing body\n");
        }
        return;
    }

    // 404 Not Found
    send_http_response(client, 404, "Not Found",
                     "text/plain", "Not Found\n");
}

// HTTP request parser — extracts method, path, headers, body
typedef struct {
    char method[16];
    char path[256];
    char headers[4096];
    char body[RECV_BUF_SIZE];
    int body_len;
    int content_length;
} http_request_t;

int parse_http_request(char* raw, int raw_len, http_request_t* req) {
    memset(req, 0, sizeof(http_request_t));

    // Find end of request line
    char* line_end = strstr(raw, "\r\n");
    if (!line_end) return -1;

    // Parse method
    char* sp1 = strchr(raw, ' ');
    if (!sp1 || sp1 > line_end) return -1;
    int method_len = (int)(sp1 - raw);
    if (method_len >= (int)sizeof(req->method)) method_len = sizeof(req->method) - 1;
    strncpy(req->method, raw, method_len);

    // Parse path
    char* path_start = sp1 + 1;
    char* sp2 = strchr(path_start, ' ');
    if (!sp2 || sp2 > line_end) return -1;
    int path_len = (int)(sp2 - path_start);
    if (path_len >= (int)sizeof(req->path)) path_len = sizeof(req->path) - 1;
    strncpy(req->path, path_start, path_len);

    // Find headers and body separator
    char* header_start = line_end + 2;
    char* body_sep = strstr(header_start, "\r\n\r\n");
    if (body_sep) {
        int hdr_len = (int)(body_sep - header_start);
        if (hdr_len >= (int)sizeof(req->headers)) hdr_len = sizeof(req->headers) - 1;
        strncpy(req->headers, header_start, hdr_len);

        // Check for Content-Length
        char* cl = strstr(req->headers, "Content-Length:");
        if (!cl) cl = strstr(req->headers, "content-length:");
        if (cl) {
            req->content_length = atoi(cl + 15);
        }

        // Copy body
        char* body_start = body_sep + 4;
        req->body_len = raw_len - (int)(body_start - raw);
        if (req->body_len > 0) {
            if (req->body_len >= (int)sizeof(req->body))
                req->body_len = sizeof(req->body) - 1;
            memcpy(req->body, body_start, req->body_len);
            req->body[req->body_len] = '\0';
        }
    }

    return 0;
}

void send_http_response(SOCKET client, int status, const char* status_text,
                        const char* content_type, const char* body) {
    char response[RECV_BUF_SIZE];
    int body_len = body ? (int)strlen(body) : 0;
    _snprintf(response, sizeof(response),
             "HTTP/1.1 %d %s\r\n"
             "Server: CloudRelay Proxy Service v1.7\r\n"
             "Content-Type: %s\r\n"
             "Content-Length: %d\r\n"
             "Connection: close\r\n"
             "\r\n"
             "%s",
             status, status_text, content_type, body_len,
             body ? body : "");
    send(client, response, (int)strlen(response), 0);
}

DWORD WINAPI handle_connection(LPVOID lpParam) {
    SOCKET client = (SOCKET)lpParam;
    char recv_buf[RECV_BUF_SIZE];
    int bytes_received;

    memset(recv_buf, 0, sizeof(recv_buf));
    bytes_received = recv(client, recv_buf, sizeof(recv_buf) - 1, 0);

    if (bytes_received > 0) {
        recv_buf[bytes_received] = '\0';

        http_request_t req;
        if (parse_http_request(recv_buf, bytes_received, &req) == 0) {
            dispatch_http(client, &req);
        } else {
            send_http_response(client, 400, "Bad Request",
                             "text/plain", "Malformed HTTP request\n");
        }
    }

    closesocket(client);
    return 0;
}

int init_winsock() {
    WSADATA wsa_data;
    int result = WSAStartup(MAKEWORD(2, 2), &wsa_data);
    if (result != 0) {
        printf("WSAStartup failed: %d\n", result);
        return 1;
    }
    return 0;
}

int main(int argc, char* argv[]) {
    SOCKET listen_socket = INVALID_SOCKET;
    SOCKET client_socket = INVALID_SOCKET;
    struct sockaddr_in server_addr, client_addr;
    int client_len = sizeof(client_addr);

    printf("[*] %s", BANNER);
    printf("[*] Starting server on port %d...\n", SERVER_PORT);

    if (init_winsock() != 0) return 1;

    init_work_buffer();
    listen_socket = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
    if (listen_socket == INVALID_SOCKET) {
        printf("[-] Socket creation failed: %d\n", WSAGetLastError());
        WSACleanup();
        return 1;
    }

    server_addr.sin_family = AF_INET;
    server_addr.sin_addr.s_addr = INADDR_ANY;
    server_addr.sin_port = htons(SERVER_PORT);

    if (bind(listen_socket, (struct sockaddr*)&server_addr, sizeof(server_addr)) == SOCKET_ERROR) {
        printf("[-] Bind failed: %d\n", WSAGetLastError());
        closesocket(listen_socket);
        WSACleanup();
        return 1;
    }

    if (listen(listen_socket, SOMAXCONN) == SOCKET_ERROR) {
        printf("[-] Listen failed: %d\n", WSAGetLastError());
        closesocket(listen_socket);
        WSACleanup();
        return 1;
    }

    printf("[+] Listening on port %d\n", SERVER_PORT);

    while (1) {
        client_socket = accept(listen_socket, (struct sockaddr*)&client_addr, &client_len);
        if (client_socket == INVALID_SOCKET) {
            printf("[-] Accept failed: %d\n", WSAGetLastError());
            continue;
        }

        printf("[+] Connection from %s:%d\n",
               inet_ntoa(client_addr.sin_addr),
               ntohs(client_addr.sin_port));

        // Handle connection in a new thread
        HANDLE thread = CreateThread(
            NULL, 0,
            (LPTHREAD_START_ROUTINE)handle_connection,
            (LPVOID)client_socket, 0, NULL
        );
        if (thread) {
            CloseHandle(thread);
        } else {
            closesocket(client_socket);
        }
    }

    closesocket(listen_socket);
    WSACleanup();
    return 0;
}
