#!/usr/bin/env python3
"""
Push String Helper — Bad-character-safe string encoding for Keystone shellcode.

Generates x86/x64 assembly that pushes a null-terminated ASCII string onto the
stack, encoding each DWORD to avoid a configurable set of bad characters.

Usage:
    Copy BAD_CHARS, _contains_bad_chars, _encode_dword, and push_string into
    your pyasm script (generated by shellgen --format pyasm). Then:

        extra = push_string("\\\\\\\\127.0.0.1\\\\share\\\\payload.exe")
        CODE += extra + "    mov edi, ecx;"   # ecx -> string after push_string

    For x64, override the default registers:

        extra = push_string("C:\\\\Windows\\\\System32\\\\cmd.exe",
                            reg="rax", ptr_reg="rcx", sp_reg="rsp")

Author: Dawid Esterhuizen
"""

import struct

# ── Configure these for your payload ────────────────────────────────────────
BAD_CHARS = {0x00, 0x0A, 0x0D}
# ────────────────────────────────────────────────────────────────────────────


def _contains_bad_chars(value_bytes):
    """Check if any byte in value_bytes is in BAD_CHARS."""
    return any(b in BAD_CHARS for b in value_bytes)


def _encode_dword(target):
    """Find a clean encoding for a dword that contains bad characters.

    Returns:
        None if no encoding needed,
        ("SUB", clean, offset) for subtraction encoding,
        ("ADD", val1, val2) for addition encoding.
    """
    target = target & 0xFFFFFFFF
    target_bytes = struct.pack("<I", target)

    if not _contains_bad_chars(target_bytes):
        return None

    # Strategy 1: subtraction (clean - offset = target)
    for inc in [1, 2, 3, 5, 7, 11, 13, 17, 0x101, 0x1001, 0x10001]:
        for mult in range(1, 1000):
            offset = inc * mult
            if offset > 0x00FFFFFF:
                break
            clean = (target + offset) & 0xFFFFFFFF
            if (not _contains_bad_chars(struct.pack("<I", clean))
                    and not _contains_bad_chars(struct.pack("<I", offset))):
                return ("SUB", clean, offset)

    # Strategy 2: addition (val1 + val2 = target)
    for val1 in range(0x01010101, 0x7F7F7F7F, 0x01010101):
        val2 = (target - val1) & 0xFFFFFFFF
        if (not _contains_bad_chars(struct.pack("<I", val1))
                and not _contains_bad_chars(struct.pack("<I", val2))):
            return ("ADD", val1, val2)

    raise ValueError(f"Cannot encode 0x{target:08x} avoiding bad chars")


def push_string(s, reg="eax", ptr_reg="ecx", sp_reg="esp"):
    """Generate assembly to push a null-terminated string onto the stack.

    Encodes each dword to avoid bad characters. After execution,
    ptr_reg points to the string on the stack.

    Args:
        s: The string to push (ASCII)
        reg: Scratch register for encoding (default: eax)
        ptr_reg: Register that gets the string pointer (default: ecx)
        sp_reg: Stack pointer register (default: esp)

    Returns:
        str: Assembly instructions (semicolon-delimited for Keystone)

    Example (x86):
        extra = push_string("\\\\\\\\127.0.0.1\\\\share\\\\test.exe")
        CODE += extra + "    mov edi, ecx;"

    Example (x64):
        extra = push_string("C:\\\\temp\\\\met.exe",
                            reg="rax", ptr_reg="rcx", sp_reg="rsp")
        CODE += extra + "    mov rdi, rcx;"
    """
    s_bytes = s.encode("ascii") + b"\x00"
    while len(s_bytes) % 4 != 0:
        s_bytes += b"\x00"

    dwords = []
    for i in range(0, len(s_bytes), 4):
        dwords.append(struct.unpack("<I", s_bytes[i:i + 4])[0])

    lines = []
    lines.append(f"    ; Push string: \"{s}\"                        ;")

    # Push dwords in reverse order (stack grows down)
    for dword in reversed(dwords):
        enc = _encode_dword(dword)
        if enc is None:
            lines.append(f"    push 0x{dword:08x}                          ;")
        elif enc[0] == "SUB":
            _, clean, offset = enc
            lines.append(
                f"    mov {reg}, 0x{clean:08x}                   ;"
                f"    sub {reg}, 0x{offset:08x}                  ;"
                f"    push {reg}                                   ;"
            )
        elif enc[0] == "ADD":
            _, val1, val2 = enc
            lines.append(
                f"    mov {reg}, 0x{val1:08x}                    ;"
                f"    add {reg}, 0x{val2:08x}                    ;"
                f"    push {reg}                                   ;"
            )

    lines.append(
        f"    mov {ptr_reg}, {sp_reg}"
        f"                              ; {ptr_reg} -> string;"
    )
    return "\n".join(lines)


# ── Demo / self-test ────────────────────────────────────────────────────────
if __name__ == "__main__":
    print("=== push_string demo (x86, BAD_CHARS = {%s}) ===" %
          ", ".join(f"0x{b:02x}" for b in sorted(BAD_CHARS)))
    print()

    test_string = "C:\\temp\\met.exe"
    asm = push_string(test_string)
    print(f"String: \"{test_string}\"")
    print(f"Assembly output:\n{asm}")
    print()

    # Verify no bad chars in any immediate values
    import re
    for match in re.finditer(r"0x([0-9a-f]{8})", asm):
        val = int(match.group(0), 16)
        val_bytes = struct.pack("<I", val)
        bad = [f"0x{b:02x}" for b in val_bytes if b in BAD_CHARS]
        if bad:
            print(f"  WARNING: {match.group(0)} contains bad chars: {bad}")
        else:
            print(f"  OK: {match.group(0)}")
