"""Base server skeleton template.

Generates the shared Winsock2 server structure: includes, main() with
socket setup, accept loop, and thread-per-connection model.
"""

from target_builder.src.config import Architecture, Compiler, ServerConfig


def generate_includes(config: ServerConfig) -> str:
    """Generate C++ #include directives."""
    includes = [
        "#include <winsock2.h>",
        "#include <ws2tcpip.h>",
        "#include <windows.h>",
        "#include <stdio.h>",
        "#include <stdlib.h>",
        "#include <string.h>",
    ]

    if config.dep and config.dep_api.value == "ntallocate":
        includes.append("#include <winternl.h>")

    return "\n".join(includes)


def generate_pragma_comment(config: ServerConfig) -> str:
    """Generate #pragma comment for Winsock library linking."""
    if config.compiler == Compiler.MINGW:
        return "#ifdef _MSC_VER\n" '#pragma comment(lib, "ws2_32.lib")\n' "#endif"
    return '#pragma comment(lib, "ws2_32.lib")'


def generate_compile_instructions(config: ServerConfig) -> str:
    """Generate header comment with compile instructions."""
    arch_label = "x86" if config.arch == Architecture.X86 else "x64"

    if config.compiler == Compiler.MINGW:
        return _mingw_compile_instructions(config, arch_label)
    return _msvc_compile_instructions(config, arch_label)


def _msvc_compile_instructions(config: ServerConfig, arch_label: str) -> str:
    """Generate MSVC compile instructions header comment."""
    prompt_type = (
        "x86 Native Tools" if config.arch == Architecture.X86 else "x64 Native Tools"
    )

    flags = ["/EHsc"]
    if config.stack_canary:
        flags.append("/GS")
    else:
        flags.append("/GS-")

    link_flags = ["ws2_32.lib"]
    if config.dep:
        link_flags.append("/NXCOMPAT")
    else:
        link_flags.append("/NXCOMPAT:NO")
    if config.aslr:
        link_flags.append("/DYNAMICBASE")
    else:
        link_flags.append("/DYNAMICBASE:NO")
    link_flags.append(f"/BASE:0x{config.base_address:08X}")
    if config.arch == Architecture.X86:
        if config.safe_seh:
            link_flags.append("/SAFESEH")
        else:
            link_flags.append("/SAFESEH:NO")

    cl_line = f"cl.exe {' '.join(flags)} server.cpp /link {' '.join(link_flags)}"

    lines = [
        "/*",
        " * Generated by target_builder - FOR AUTHORIZED SECURITY TESTING ONLY",
        f" * Architecture: {arch_label}",
        f" * Compile from: Visual Studio {prompt_type} Command Prompt",
        " *",
        f" *   {cl_line}",
        " */",
    ]
    return "\n".join(lines)


def _mingw_compile_instructions(config: ServerConfig, arch_label: str) -> str:
    """Generate MinGW cross-compile instructions header comment."""
    if config.arch == Architecture.X86:
        compiler = "i686-w64-mingw32-g++"
    else:
        compiler = "x86_64-w64-mingw32-g++"

    cxx_flags = []
    if config.stack_canary:
        cxx_flags.append("-fstack-protector")
    else:
        cxx_flags.append("-fno-stack-protector")

    from target_builder.src.config import VulnType

    if config.vuln_type == VulnType.SEH:
        cxx_flags.append("-fseh-exceptions")

    link_flags = ["-lws2_32", "-static"]
    if config.dep:
        link_flags.append("-Wl,--nxcompat")
    else:
        link_flags.append("-Wl,--disable-nxcompat")
    if config.aslr:
        link_flags.append("-Wl,--dynamicbase")
    else:
        link_flags.append("-Wl,--disable-dynamicbase")
    link_flags.append(f"-Wl,--image-base,0x{config.base_address:08X}")

    flags_str = " ".join(cxx_flags) if cxx_flags else ""
    link_str = " ".join(link_flags)
    compile_line = f"{compiler} {flags_str} server.cpp -o server.exe {link_str}"

    lines = [
        "/*",
        " * Generated by target_builder - FOR AUTHORIZED SECURITY TESTING ONLY",
        f" * Architecture: {arch_label}",
        f" * Compiler: MinGW ({compiler})",
        " *",
        f" *   {compile_line}",
        " *",
        " * To test on Linux: wine ./server.exe",
        " */",
    ]
    return "\n".join(lines)


def generate_globals(config: ServerConfig) -> str:
    """Generate global variables (port, banner, recv buffer size)."""
    banner_escaped = config.banner.replace("\\", "\\\\").replace('"', '\\"')
    return f"""\
#define SERVER_PORT {config.port}
#define RECV_BUF_SIZE 8192
#define BANNER "{banner_escaped}\\n"
"""


def generate_info_leak_function(config: ServerConfig) -> str:
    """Generate a small utility function whose address is leaked via ASLR info leak.

    The attacker sees the leaked pointer, finds this function in the binary
    (e.g. via IDA/Ghidra), and subtracts the offset to compute the EXE base.
    """
    if not config.aslr:
        return ""

    name = config.leak_func_name
    return f"""\
// Internal utility function
int {name}(void) {{
    return SERVER_PORT;
}}
"""


def generate_dep_api_usage(config: ServerConfig) -> str:
    """Generate legitimate usage of the DEP bypass API.

    The selected API is called for a real purpose so it appears in the IAT.
    """
    if not config.dep:
        return ""

    _DEP_API_CODE = {
        "virtualprotect": """\
// Legitimate use of VirtualProtect for configuration buffer
void init_config_buffer() {
    static char config_buf[4096];
    DWORD old_protect;
    // Re-protect config as read-only after initialization
    memset(config_buf, 0, sizeof(config_buf));
    strcpy(config_buf, "server_config_v1");
    VirtualProtect(config_buf, sizeof(config_buf), PAGE_READONLY, &old_protect);
}
""",
        "virtualalloc": """\
// Legitimate use of VirtualAlloc for working buffer
static char* g_work_buffer = NULL;

void init_work_buffer() {
    g_work_buffer = (char*)VirtualAlloc(
        NULL, 65536, MEM_COMMIT | MEM_RESERVE, PAGE_READWRITE
    );
    if (g_work_buffer) {
        memset(g_work_buffer, 0, 65536);
    }
}
""",
        "writeprocessmemory": """\
// Legitimate use of WriteProcessMemory for function pointer patching
typedef void (*handler_func_t)(void);
static handler_func_t g_handler_table[16] = {0};

void patch_handler_table(int index, handler_func_t new_handler) {
    if (index >= 0 && index < 16) {
        SIZE_T written;
        WriteProcessMemory(
            GetCurrentProcess(),
            &g_handler_table[index],
            &new_handler,
            sizeof(handler_func_t),
            &written
        );
    }
}
""",
        "heapcreate": """\
// Legitimate use of HeapCreate/HeapAlloc for connection data
static HANDLE g_conn_heap = NULL;

void init_connection_heap() {
    g_conn_heap = HeapCreate(0, 1024 * 64, 1024 * 1024);
}

void* alloc_conn_data(SIZE_T size) {
    if (g_conn_heap) {
        return HeapAlloc(g_conn_heap, HEAP_ZERO_MEMORY, size);
    }
    return malloc(size);
}

void free_conn_data(void* ptr) {
    if (g_conn_heap) {
        HeapFree(g_conn_heap, 0, ptr);
    } else {
        free(ptr);
    }
}
""",
        "setprocessdeppolicy": """\
// Legacy compatibility check using SetProcessDEPPolicy
void check_dep_compat() {
    // Attempt to query DEP status (legacy Vista/XP method)
    // This call will fail on modern Windows but the import remains
    SetProcessDEPPolicy(0);
}
""",
        "ntallocate": """\
// Low-level allocation wrapper using NtAllocateVirtualMemory
typedef NTSTATUS (NTAPI *pNtAllocateVirtualMemory)(
    HANDLE, PVOID*, ULONG_PTR, PSIZE_T, ULONG, ULONG
);

static pNtAllocateVirtualMemory NtAllocVm = NULL;

void init_nt_alloc() {
    HMODULE ntdll = GetModuleHandleA("ntdll.dll");
    if (ntdll) {
        NtAllocVm = (pNtAllocateVirtualMemory)GetProcAddress(
            ntdll, "NtAllocateVirtualMemory"
        );
    }
}

void* nt_alloc_buffer(SIZE_T size) {
    if (NtAllocVm) {
        PVOID base = NULL;
        SIZE_T region_size = size;
        NTSTATUS status = NtAllocVm(
            GetCurrentProcess(), &base, 0, &region_size,
            MEM_COMMIT | MEM_RESERVE, PAGE_READWRITE
        );
        if (status == 0) return base;
    }
    return VirtualAlloc(NULL, size, MEM_COMMIT | MEM_RESERVE, PAGE_READWRITE);
}
""",
    }

    return _DEP_API_CODE.get(config.dep_api.value, "")


def generate_winsock_init() -> str:
    """Generate WSAStartup / WSACleanup helper."""
    return """\
int init_winsock() {
    WSADATA wsa_data;
    int result = WSAStartup(MAKEWORD(2, 2), &wsa_data);
    if (result != 0) {
        printf("WSAStartup failed: %d\\n", result);
        return 1;
    }
    return 0;
}
"""


def generate_main_function(config: ServerConfig) -> str:
    """Generate main() with socket setup, bind, listen, accept loop."""
    dep_init_call = ""
    if config.dep:
        api = config.dep_api.value
        if api == "virtualprotect":
            dep_init_call = "    init_config_buffer();\n"
        elif api == "virtualalloc":
            dep_init_call = "    init_work_buffer();\n"
        elif api == "heapcreate":
            dep_init_call = "    init_connection_heap();\n"
        elif api == "setprocessdeppolicy":
            dep_init_call = "    check_dep_compat();\n"
        elif api == "ntallocate":
            dep_init_call = "    init_nt_alloc();\n"

    rop_dll_load = ""
    if config.rop_dll.enabled:
        dll_name = config.rop_dll.output_file.replace(".cpp", ".dll")
        rop_dll_load = f"""\
    // Load ROP helper DLL
    HMODULE hRopDll = LoadLibraryA("{dll_name}");
    if (hRopDll) {{
        typedef void (*init_fn)();
        init_fn rop_init = (init_fn)GetProcAddress(hRopDll, "RopHelperInit");
        if (rop_init) rop_init();
        printf("[+] Loaded ROP helper DLL\\n");
    }}

"""

    return f"""\
int main(int argc, char* argv[]) {{
    SOCKET listen_socket = INVALID_SOCKET;
    SOCKET client_socket = INVALID_SOCKET;
    struct sockaddr_in server_addr, client_addr;
    int client_len = sizeof(client_addr);

    printf("[*] %s", BANNER);
    printf("[*] Starting server on port %d...\\n", SERVER_PORT);

    if (init_winsock() != 0) return 1;

{dep_init_call}{rop_dll_load}\
    listen_socket = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
    if (listen_socket == INVALID_SOCKET) {{
        printf("[-] Socket creation failed: %d\\n", WSAGetLastError());
        WSACleanup();
        return 1;
    }}

    server_addr.sin_family = AF_INET;
    server_addr.sin_addr.s_addr = INADDR_ANY;
    server_addr.sin_port = htons(SERVER_PORT);

    if (bind(listen_socket, (struct sockaddr*)&server_addr, sizeof(server_addr)) == SOCKET_ERROR) {{
        printf("[-] Bind failed: %d\\n", WSAGetLastError());
        closesocket(listen_socket);
        WSACleanup();
        return 1;
    }}

    if (listen(listen_socket, SOMAXCONN) == SOCKET_ERROR) {{
        printf("[-] Listen failed: %d\\n", WSAGetLastError());
        closesocket(listen_socket);
        WSACleanup();
        return 1;
    }}

    printf("[+] Listening on port %d\\n", SERVER_PORT);

    while (1) {{
        client_socket = accept(listen_socket, (struct sockaddr*)&client_addr, &client_len);
        if (client_socket == INVALID_SOCKET) {{
            printf("[-] Accept failed: %d\\n", WSAGetLastError());
            continue;
        }}

        printf("[+] Connection from %s:%d\\n",
               inet_ntoa(client_addr.sin_addr),
               ntohs(client_addr.sin_port));

        // Handle connection in a new thread
        HANDLE thread = CreateThread(
            NULL, 0,
            (LPTHREAD_START_ROUTINE)handle_connection,
            (LPVOID)client_socket, 0, NULL
        );
        if (thread) {{
            CloseHandle(thread);
        }} else {{
            closesocket(client_socket);
        }}
    }}

    closesocket(listen_socket);
    WSACleanup();
    return 0;
}}"""
