"""ROP companion DLL template.

Generates a C++ DLL source with inline assembly (__asm) blocks containing
useful ROP gadgets at three density levels (minimal, standard, full).
x86 only — __asm blocks are MSVC x86 specific.
"""

from target_builder.src.config import GadgetDensity, RopDllConfig


def generate_embedded_gadgets(density: GadgetDensity) -> str:
    """Generate ROP gadget functions for embedding directly in the server source.

    Unlike generate_rop_dll(), this produces only the gadget functions without
    DLL boilerplate (no DllMain, no dllexport, no compile header).
    Includes a volatile reference array to prevent the linker from stripping
    unreferenced functions.

    Args:
        density: Gadget density level.

    Returns:
        C++ function blocks as a string.
    """
    gadgets = _generate_gadget_functions(density)

    # Collect function names so we can create a linker anti-strip reference
    func_names = []
    for line in gadgets.split("\n"):
        if "void " in line and "(" in line and "__declspec" in line:
            # Extract function name from: __declspec(noinline) void FuncName() {
            name = line.split("void ")[1].split("(")[0].strip()
            func_names.append(name)

    # Create a volatile pointer array that references each gadget function.
    # This prevents MSVC from stripping the functions as unreferenced.
    ref_lines = [
        "// Prevent linker from stripping unreferenced gadget functions",
        "volatile void* _gadget_refs[] = {",
    ]
    for name in func_names:
        ref_lines.append(f"    (void*)&{name},")
    ref_lines.append("};")

    return "// --- Embedded ROP gadgets ---\n\n" + gadgets + "\n\n" + "\n".join(
        ref_lines
    )


def generate_rop_dll(config: RopDllConfig) -> str:
    """Generate complete ROP companion DLL C++ source.

    Args:
        config: ROP DLL configuration.

    Returns:
        Complete C++ source as a string.
    """
    base_hex = f"0x{config.base_address:08X}"

    parts = [
        _generate_header(base_hex),
        _generate_gadget_functions(config.gadget_density),
        _generate_dllmain(),
        _generate_init_export(),
    ]

    return "\n\n".join(parts)


def generate_dll_build_command(config: RopDllConfig) -> str:
    """Generate the cl.exe command to compile the DLL."""
    output = config.output_file
    base_hex = f"0x{config.base_address:08X}"

    flags = ["/LD", "/GS-"]
    link_flags = [
        f"/BASE:{base_hex}",
        "/DYNAMICBASE:NO" if config.no_aslr else "/DYNAMICBASE",
        "/SAFESEH:NO",
        "/NXCOMPAT:NO",
    ]

    return f"cl.exe {' '.join(flags)} {output} /link {' '.join(link_flags)}"


def _generate_header(base_hex: str) -> str:
    """Generate DLL header with compile instructions."""
    return f"""\
/*
 * ROP Helper DLL - Generated by target_builder
 * FOR AUTHORIZED SECURITY TESTING ONLY
 *
 * This DLL contains inline assembly gadgets for ROP chain practice.
 * Compile from: Visual Studio x86 Native Tools Command Prompt
 *
 *   cl.exe /LD /GS- rop_helper.cpp /link /BASE:{base_hex} /DYNAMICBASE:NO /SAFESEH:NO /NXCOMPAT:NO
 */

#include <windows.h>
#include <stdio.h>"""


def _generate_gadget_functions(density: GadgetDensity) -> str:
    """Generate functions containing inline assembly gadgets."""
    functions = []

    # Minimal gadgets — always included
    functions.append(_gadgets_minimal())

    if density in (GadgetDensity.STANDARD, GadgetDensity.FULL):
        functions.append(_gadgets_standard())

    if density == GadgetDensity.FULL:
        functions.append(_gadgets_full())

    return "\n\n".join(functions)


def _gadgets_minimal() -> str:
    """Bare essentials: pop reg; ret, jmp esp, push esp; ret."""
    return """\
// --- Minimal gadget set ---

__declspec(noinline) void HelperInit() {
    __asm {
        // pop eax; ret
        pop eax
        ret

        // pop ecx; ret
        pop ecx
        ret

        // pop edx; ret
        pop edx
        ret

        // jmp esp
        jmp esp

        // push esp; ret
        push esp
        ret
    }
}

__declspec(noinline) void HelperValidate() {
    __asm {
        // pop ebx; ret
        pop ebx
        ret

        // pop esi; ret
        pop esi
        ret

        // pop edi; ret
        pop edi
        ret

        // pop ebp; ret
        pop ebp
        ret
    }
}"""


def _gadgets_standard() -> str:
    """Working exploit set: pivots, write-what-where, arithmetic."""
    return """\
// --- Standard gadget set ---

__declspec(noinline) void ProcessData() {
    __asm {
        // pop pop ret (for SEH)
        pop esi
        pop edi
        ret

        // xchg eax, esp; ret (stack pivot)
        xchg eax, esp
        ret

        // mov [eax], ecx; ret (write-what-where)
        mov [eax], ecx
        ret

        // add esp, 8; ret (skip 8 bytes on stack)
        add esp, 0x08
        ret

        // add esp, 0x10; ret (skip 16 bytes)
        add esp, 0x10
        ret
    }
}

__declspec(noinline) void ValidateInput() {
    __asm {
        // inc eax; ret
        inc eax
        ret

        // dec eax; ret
        dec eax
        ret

        // inc ecx; ret
        inc ecx
        ret

        // dec ecx; ret
        dec ecx
        ret

        // xor eax, eax; ret (zero eax)
        xor eax, eax
        ret

        // neg eax; ret (negate)
        neg eax
        ret
    }
}

__declspec(noinline) void TransformBuffer() {
    __asm {
        // mov eax, ecx; ret
        mov eax, ecx
        ret

        // mov ecx, eax; ret
        mov ecx, eax
        ret

        // add eax, ecx; ret
        add eax, ecx
        ret

        // sub eax, ecx; ret
        sub eax, ecx
        ret

        // push eax; pop ecx; ret
        push eax
        pop ecx
        ret
    }
}"""


def _gadgets_full() -> str:
    """Rich gadget surface: multiple pivots, conditionals, varied endings."""
    return """\
// --- Full gadget set ---

__declspec(noinline) void AnalyzeStream() {
    __asm {
        // Stack pivot variants
        xchg eax, esp
        ret

        xchg ecx, esp
        ret

        // mov esp, eax; ret
        mov esp, eax
        ret

        // add esp, 0x20; ret (large skip)
        add esp, 0x20
        ret

        // add esp, 0x40; ret
        add esp, 0x40
        ret

        // pop pop pop ret
        pop eax
        pop ecx
        pop edx
        ret
    }
}

__declspec(noinline) void CompressPayload() {
    __asm {
        // Memory read gadgets
        // mov eax, [ecx]; ret
        mov eax, [ecx]
        ret

        // mov eax, [eax]; ret
        mov eax, [eax]
        ret

        // mov ecx, [edx]; ret
        mov ecx, [edx]
        ret

        // Arithmetic chains
        // add eax, ebx; ret
        add eax, ebx
        ret

        // sub eax, ebx; ret
        sub eax, ebx
        ret

        // and eax, ecx; ret
        and eax, ecx
        ret

        // or eax, ecx; ret
        or eax, ecx
        ret
    }
}

__declspec(noinline) void EncodeResult() {
    __asm {
        // Gadgets with ret N
        pop eax
        ret 4

        pop ecx
        ret 8

        // call reg variants
        push eax
        call eax

        push ecx
        call ecx

        // jmp reg variants
        jmp eax
        jmp ecx

        // Write gadgets
        // mov [ecx], eax; ret
        mov [ecx], eax
        ret

        // mov [edx], eax; ret
        mov [edx], eax
        ret

        // mov [eax+4], ecx; ret
        mov [eax+4], ecx
        ret
    }
}

__declspec(noinline) void DecryptBlock() {
    __asm {
        // Shift operations
        shl eax, 1
        ret

        shr eax, 1
        ret

        rol eax, 1
        ret

        ror eax, 1
        ret

        // Exchange variants
        xchg eax, ecx
        ret

        xchg eax, edx
        ret

        xchg eax, ebx
        ret

        // pushad; ret (push all general registers)
        pushad
        ret

        // popad; ret (pop all general registers)
        popad
        ret
    }
}"""


def _generate_dllmain() -> str:
    """Generate DllMain entry point."""
    return """\
BOOL APIENTRY DllMain(HMODULE hModule, DWORD reason, LPVOID reserved) {
    switch (reason) {
    case DLL_PROCESS_ATTACH:
        DisableThreadLibraryCalls(hModule);
        break;
    case DLL_PROCESS_DETACH:
        break;
    }
    return TRUE;
}"""


def _generate_init_export() -> str:
    """Generate the exported init function the server calls."""
    return """\
// Exported function called by the server after LoadLibrary
extern "C" __declspec(dllexport) void RopHelperInit() {
    printf("[+] ROP Helper DLL initialized\\n");
}"""
