#!/usr/bin/env python3
"""
ROR13 Hash Generator for Windows API Functions

This tool generates ROR13 hashes used in shellgen for dynamic API resolution.
The ROR13 algorithm is commonly used in position-independent shellgen to
locate Windows API functions by hash instead of by name.

Usage:
    # Generate hash for a single function
    ./hash_generator.py GetProcAddress

    # Generate hashes for multiple functions
    ./hash_generator.py LoadLibraryA GetProcAddress ExitProcess

    # Generate hashes from a file (one function per line)
    ./hash_generator.py --file api_functions.txt

    # Output as Python dict
    ./hash_generator.py --format python LoadLibraryA GetProcAddress

    # Output as C array
    ./hash_generator.py --format c LoadLibraryA GetProcAddress

Author: Dawid Esterhuizen
"""

import argparse
import sys


def ror13_hash(name):
    """
    Calculate ROR13 hash for a function name.

    The ROR13 algorithm:
    1. Start with hash = 0
    2. For each character in the function name:
       - Rotate hash right by 13 bits
       - Add the character's ASCII value
    3. Return the 32-bit hash

    Args:
        name: Function name (case-sensitive for Windows APIs)

    Returns:
        int: 32-bit ROR13 hash value
    """
    h = 0
    for c in name:
        # Rotate right by 13 bits (32-bit value)
        h = ((h >> 13) | (h << 19)) & 0xFFFFFFFF
        # Add character value
        h = (h + ord(c)) & 0xFFFFFFFF
    return h


def ror13_hash_case_insensitive(name):
    """
    Calculate ROR13 hash with case-insensitive comparison.
    Converts the name to uppercase before hashing (Windows convention).

    Args:
        name: Function name

    Returns:
        int: 32-bit ROR13 hash value
    """
    return ror13_hash(name.upper())


def generate_hash_dict(functions, case_insensitive=False):
    """
    Generate a dictionary of function names to hash values.

    Args:
        functions: List of function names
        case_insensitive: If True, convert to uppercase before hashing

    Returns:
        dict: Mapping of function name to hash value
    """
    hash_func = ror13_hash_case_insensitive if case_insensitive else ror13_hash
    return {func: hash_func(func) for func in functions}


def format_output_text(hash_dict):
    """Format output as human-readable text."""
    output = []
    output.append("=" * 72)
    output.append("ROR13 Hash Generator")
    output.append("=" * 72)
    output.append("")

    # Calculate padding for alignment
    max_name_len = max(len(name) for name in hash_dict.keys())

    for func_name, hash_value in hash_dict.items():
        output.append(f"{func_name:<{max_name_len}}  =>  0x{hash_value:08x}")

    output.append("")
    output.append("=" * 72)
    output.append(f"Total functions: {len(hash_dict)}")
    output.append("=" * 72)

    return "\n".join(output)


def format_output_python(hash_dict):
    """Format output as Python dictionary."""
    output = []
    output.append("# ROR13 Hash Dictionary")
    output.append("# Generated by hash_generator.py")
    output.append("")
    output.append("API_HASHES = {")

    for func_name, hash_value in hash_dict.items():
        output.append(f"    '{func_name}': 0x{hash_value:08x},")

    output.append("}")

    return "\n".join(output)


def format_output_c(hash_dict):
    """Format output as C struct array."""
    output = []
    output.append("// ROR13 Hash Definitions")
    output.append("// Generated by hash_generator.py")
    output.append("")
    output.append("typedef struct {")
    output.append("    const char *name;")
    output.append("    unsigned int hash;")
    output.append("} ApiHash;")
    output.append("")
    output.append("ApiHash api_hashes[] = {")

    for func_name, hash_value in hash_dict.items():
        output.append(f'    {{"{func_name}", 0x{hash_value:08x}}},')

    output.append("};")
    output.append("")
    output.append(f"#define API_HASH_COUNT {len(hash_dict)}")

    return "\n".join(output)


def format_output_asm(hash_dict):
    """Format output as assembly constants."""
    output = []
    output.append("; ROR13 Hash Definitions")
    output.append("; Generated by hash_generator.py")
    output.append("")

    for func_name, hash_value in hash_dict.items():
        # Create a valid assembly constant name
        const_name = func_name.upper() + "_HASH"
        output.append(f"{const_name:<30} equ 0x{hash_value:08x}  ; {func_name}")

    return "\n".join(output)


def format_output_json(hash_dict):
    """Format output as JSON."""
    import json

    # Convert int keys to hex strings for JSON
    json_dict = {name: f"0x{hash_val:08x}" for name, hash_val in hash_dict.items()}

    return json.dumps(json_dict, indent=2)


def read_functions_from_file(filepath):
    """
    Read function names from a file (one per line).

    Args:
        filepath: Path to file containing function names

    Returns:
        list: List of function names (empty lines and comments ignored)
    """
    functions = []
    try:
        with open(filepath, "r") as f:
            for line in f:
                line = line.strip()
                # Skip empty lines and comments
                if line and not line.startswith("#"):
                    functions.append(line)
        return functions
    except FileNotFoundError:
        print(f"Error: File not found: {filepath}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"Error reading file: {e}", file=sys.stderr)
        sys.exit(1)


def create_parser():
    """Create and configure the argument parser."""
    parser = argparse.ArgumentParser(
        description="Generate ROR13 hashes for Windows API functions",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Single function hash
  %(prog)s LoadLibraryA

  # Multiple functions
  %(prog)s LoadLibraryA GetProcAddress ExitProcess

  # From file
  %(prog)s --file api_list.txt

  # Python format
  %(prog)s --format python LoadLibraryA GetProcAddress

  # Case-insensitive (Windows convention)
  %(prog)s --case-insensitive loadlibrarya getprocaddress

Common Windows API Functions:
  kernel32.dll: LoadLibraryA, GetProcAddress, ExitProcess, CreateProcessA,
                WinExec, VirtualAlloc, VirtualProtect, WriteProcessMemory

  user32.dll:   MessageBoxA, MessageBoxW

  ws2_32.dll:   WSAStartup, WSASocketA, WSAConnect, connect, send, recv

  ntdll.dll:    NtAllocateVirtualMemory, NtProtectVirtualMemory
        """,
    )

    parser.add_argument("functions", nargs="*", help="Function names to hash")

    parser.add_argument(
        "--file", "-", help="Read function names from file (one per line)"
    )

    parser.add_argument(
        "--format",
        choices=["text", "python", "c", "asm", "json"],
        default="text",
        help="Output format (default: text)",
    )

    parser.add_argument(
        "--case-insensitive",
        "-i",
        action="store_true",
        help="Convert to uppercase before hashing (Windows convention)",
    )

    parser.add_argument(
        "--verify",
        help="Verify hash against expected value (format: FunctionName:0x12345678)",
    )

    parser.add_argument(
        "--generate-completion",
        choices=["bash", "zsh"],
        metavar="SHELL",
        help="Print shell completion script and exit",
    )

    return parser


def main():
    """Main entry point."""
    import os

    sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
    from lib.completions import handle_completion

    if handle_completion(
        sys.argv[1:],
        create_parser,
        ["hash_generator", "hash_generator.py"],
    ):
        return

    parser = create_parser()
    args = parser.parse_args()

    # Collect function names
    functions = []

    if args.file:
        functions.extend(read_functions_from_file(args.file))

    if args.functions:
        functions.extend(args.functions)

    # Verify mode
    if args.verify:
        parts = args.verify.split(":")
        if len(parts) != 2:
            print(
                "Error: --verify format should be FunctionName:0xHASH", file=sys.stderr
            )
            sys.exit(1)

        func_name = parts[0]
        expected_hash = int(parts[1], 16)

        if args.case_insensitive:
            actual_hash = ror13_hash_case_insensitive(func_name)
        else:
            actual_hash = ror13_hash(func_name)

        print(f"Function: {func_name}")
        print(f"Expected: 0x{expected_hash:08x}")
        print(f"Actual:   0x{actual_hash:08x}")

        if actual_hash == expected_hash:
            print("✓ MATCH")
            sys.exit(0)
        else:
            print("✗ MISMATCH")
            sys.exit(1)

    if not functions:
        print("Error: No function names provided", file=sys.stderr)
        print("Use --help for usage information", file=sys.stderr)
        sys.exit(1)

    # Generate hashes
    hash_dict = generate_hash_dict(functions, args.case_insensitive)

    # Format output
    formatters = {
        "text": format_output_text,
        "python": format_output_python,
        "c": format_output_c,
        "asm": format_output_asm,
        "json": format_output_json,
    }

    output = formatters[args.format](hash_dict)
    print(output)


if __name__ == "__main__":
    main()
